mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('tutor_me.urls')),
    path('tutor_me/', include('tutor_me.urls')),
    path('admin/', admin.site.urls),
    path("", include("allauth.urls")),
]

tutor_me/urls.py
from django.urls import path, include

from . import views

app_name = 'tutor_me'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('', include("allauth.urls")),
    path('redirect/', views.view_redirect, name='redirect'),
    path('tutor/', views.tutor, name='tutor'),
    path('student/', views.student, name='student'),
    # path('tutor/availability/', views.save_availability, name='availability'),
    # path('tutor/availability/', views.available_times, name='availability_list'),
    path('student/schedule/submit_request',
         views.submit_request, name='submit_request'),
    path('student/schedule/success/', views.success, name='success'),
    ]

tutor_me/models.py
'''
REFERENCES

Title: GPT-3.5 Language Model
Author: OpenAI
Date: 2021-09
Code version: 3.5
URL: https://openai.com/
Software License: <OpenAI API Terms of Service>
Note: Used for the Django built in relationships
'''

from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.contrib.postgres.fields import ArrayField
from django.utils import timezone
from django.contrib import admin


# Create your models here.
class Rate(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    rate = models.IntegerField(default=0)

class Availability(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    start = models.DateTimeField(default=timezone.now)
    end = models.DateTimeField(default=timezone.now)

# Some code from GPT-3.5 Language Model
class Course(models.Model):
    user = models.ManyToManyField(User)
    mnemonic = models.CharField(max_length=10, null=True)
    number = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=200, null=True)

# Some code from GPT-3.5 Language Model
class Appointment(models.Model):
     availability = models.ForeignKey(Availability, null=True, on_delete=models.CASCADE)
     course = models.ForeignKey(Course, null=True, on_delete=models.CASCADE)
     student = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
     start = models.DateTimeField(default=timezone.now)
     end = models.DateTimeField(default=timezone.now)
     confirmed = models.BooleanField(default=False)
     note = models.CharField(max_length=200, null=True)


class RequestNotification(models.Model):
    student = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    notification = models.CharField(max_length=200, null=True)

tutor_me/forms.py
from django import forms
from .models import Availability


# class AvailabilityForm(forms.ModelForm):
#     class Meta:
#         model = Availability
#         fields = ('start', 'end')
#         widgets = {
#             'start': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
#             'end': forms.DateTimeInput(attrs={'type': 'datetime-local'})
#         }

tutor_me/views.py
'''
REFERENCES

Title: GPT-3.5 Language Model
Author: OpenAI
Date: 2021-09
Code version: 3.5
URL: https://openai.com/
Software License: <OpenAI API Terms of Service>
Note: Nearly exclusively used for accessing Django objects and their built-in functions

Title: User Registration in Django using Google OAuth
Author: Geoffrey Mungai
Date: 2020-12
Code version: N/A
URL: https://www.section.io/engineering-education/django-google-oauth/
Software License: N/A
Note: Used for the google authentication login
'''

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.models import Group
from datetime import datetime, timedelta
import pytz
import requests
from tutor_me.models import Course, Appointment, Availability, RequestNotification, Rate


def get_url_page(page):
    url = "https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01&term=1228&page=" + \
        str(page)
    return requests.get(url).json()


def set_classes():
    counter = 1
    url_list = get_url_page(counter)
    done = {}
    while len(url_list) > 0:
        for c in url_list:
            if c['subject'] + c["catalog_nbr"] not in done:
                course = Course(number=c['catalog_nbr'], mnemonic=c['subject'], name=c['descr'],)
                course.save()
                done[c['subject'] + c["catalog_nbr"]] = True
        counter += 1
        url_list = get_url_page(counter)


def is_student(user):
    return user.groups.filter(name='student').exists()


def is_tutor(user):
    return user.groups.filter(name='tutor').exists()


def is_not_registered(user):
    return is_student(user) or is_tutor(user)


def get_user(request):
    return request.user


def get_url_page(page):
    url = "https://sisuva.admin.virginia.edu/psc/ihprd/UVSS/SA/s/WEBLIB_HCX_CM.H_CLASS_SEARCH.FieldFormula.IScript_ClassSearch?institution=UVA01&term=1228&page=" + \
        str(page)
    return requests.get(url).json()

# Some code from GPT-3.5 Language Model
def get_classes():
    # retrieve all Course objects from the database
    courses = Course.objects.all()

    # construct the list of strings
    classes = [f"{course.mnemonic} {course.number} - {course.name}" for course in courses]
    # classes = list(set(classes))
    # classes.sort()
    return classes

def get_course_str(course):
    se_list = course.split()
    mnemonic = se_list[0]
    number = se_list[1]
    return [mnemonic, number]

# Some code from GPT-3.5 Language Model
def tutor(request):

    #set_classes()
    user = get_user(request)
    if not is_tutor(user):
        return HttpResponse("You are not logged in as a tutor, so you cannot view this page.")
    user_classes = user.course_set.all()
    classes = get_classes()
    current_time = datetime.now()
    all_available = Availability.objects.filter(user=request.user, end__gt=current_time)
    requests = Appointment.objects.filter(availability__user=user, end__gt=current_time)
    appts = requests.filter(confirmed=True)
    rate_obs = Rate.objects.filter(user=user)
    username = user.first_name + " " + user.last_name
    rate = ""
    if rate_obs:
        rate = rate_obs[0].rate


    context = {
        "classes": classes, "timeslots": all_available, "user_classes": user_classes,
        "requests":requests, "appointments": appts, "rate": rate, "username": username,
        }

    if rate:
        context["int_rate"] = int(rate)

    # Set hourly rate
    try:
        rate = request.POST.get("set_rate")
        all_rates = Rate.objects.all()
        int_rate = int(rate)
        context['int_rate'] = int_rate
        for rates in all_rates:
            if rates.user == user:
                rates.rate = int(rate)
                rates.save()
                context['rate'] = rate
                return render(request, 'tutor_me/tutor_view.html', context)
        else:
            hourly_rate = Rate(user=user, rate=int(rate))
            hourly_rate.save()
            context['rate'] = rate
            return render(request, 'tutor_me/tutor_view.html', context)


    except:
        pass


    # Dropdown Request Process
    try:
        search = request.POST['class-dropdown']
        se_list = search.split()
        mnemonic = se_list[0]
        number = se_list[1]
        course = get_object_or_404(Course, number=number, mnemonic=mnemonic)
        user.course_set.add(course)
        return render(request, 'tutor_me/tutor_view.html', context)
    except:
        pass

    # Delete tutor class
    try:
        tutor_class_id = request.POST.get('tutor_class_id')
        if tutor_class_id:
            user.course_set.remove(tutor_class_id)
            return render(request, 'tutor_me/tutor_view.html', context)
    except:
        pass

    # Availability Form Process

    try:
        #available = request.POST['save_availability']
        start_time = request.POST.get('start_time')
        end_time = request.POST.get('end_time')
        if end_time <= start_time:
            context["error_message"] = "Invalid times entered. Start time must come before end time. Please try again."
            return render(request, 'tutor_me/tutor_view.html', context)
        my_start = datetime.strptime(start_time, '%Y-%m-%dT%H:%M')
        my_end = datetime.strptime(end_time, '%Y-%m-%dT%H:%M')
        if my_start.date() != my_end.date():
            context["error_message"] = "Invalid times entered. Start and end time must be on the same day. Please try again."
            return render(request, 'tutor_me/tutor_view.html', context)
        available_times = Availability.objects.filter(user=request.user, end__gt=current_time)
        for availi in available_times:
            eastern_timezone = pytz.timezone('US/Eastern')
            if availi.start <= my_start.astimezone(eastern_timezone)+timedelta(hours=1) <= availi.end \
                    or availi.start <= my_end.astimezone(eastern_timezone)+timedelta(hours=1) <= availi.end:
                context["error_message"] = "Invalid times entered. Times cannot conflict with another availability " \
                                           "slot. Please try again. "
                return render(request, 'tutor_me/tutor_view.html', context)
        availability = Availability(start=my_start, end=my_end, user=user)
        availability.save()

        context["timeslots"] = Availability.objects.filter(user=request.user, end__gt=current_time)
        return render(request, 'tutor_me/tutor_view.html', context)
    except:
        pass
    #delete available slots if needed
    try:
        avail_id = request.POST.get('delete_avail_id')
        if avail_id:
            avail = all_available.get(id=avail_id)
            avail.delete()
            return render(request, 'tutor_me/tutor_view.html', context)
    except:
        pass

    #handle student appointment requests
    #--------->accept request
    try:
        request_id = request.POST.get('request_accept')
        if request_id:
            req_yes = requests.get(id=request_id)
            req_yes.confirmed=True
            req_yes.save()
            return render(request, 'tutor_me/tutor_view.html', context)
    except:
        pass

    #--------->deny request
    try:
        request_id = request.POST.get('request_deny')
        if request_id:
            req_no = requests.get(id=request_id)
            notification = "Your request with " + req_no.availability.user.first_name
            notification += " " + req_no.availability.user.last_name + " for " + req_no.course.mnemonic
            notification += " " + req_no.course.number + " on " + (req_no.end+timedelta(hours=-5)).strftime("%B%e")
            notification += " from " + (req_no.start+timedelta(hours=-5)).strftime("%I:%M %p") + " to "
            notification += (req_no.end+timedelta(hours=-5)).strftime("%I:%M %p") + " was denied."
            notif = RequestNotification(student=req_no.student, notification=notification)
            notif.save()
            req_no.delete()
            return render(request, 'tutor_me/tutor_view.html', context)
    except:
        pass

    return render(request, 'tutor_me/tutor_view.html', context)



def view_redirect(request):
    user = get_user(request)
    error = False
    try:
        selected_choice = request.POST['group']
    except:
        error = True
        pass
    if not error:
        user.groups.add(selected_choice)
        user.save()
    if is_student(user):
        return student(request, is_redirect=True)
    elif is_tutor(user):
        return tutor(request)
    # DOES NOT ALLOW FOR CHANGING GROUP
    return HttpResponse("Error at view_redirect")


def index(request):
    user = get_user(request)
    anon = user.is_anonymous
    if anon:
        return render(request, 'tutor_me/google_login.html')
    elif not anon and (is_tutor(user) or is_student(user)):
        return view_redirect(request)
    else:
        groups = Group.objects
        return render(request, 'tutor_me/signup.html', {'user': user, 'groups': groups})

# User Registration in Django using Google OAuth
def login(request):
    return render(request, 'tutor_me/google_login.html')

# Some code from GPT-3.5 Language Model
def student(request, is_redirect=False):
    user = get_user(request)
    if is_student(user):
        notifications = RequestNotification.objects.filter(student=request.user)
        requests = Appointment.objects.filter(student=user)
        current_time = datetime.now()
        appts = requests.filter(confirmed=True, end__gt=current_time)
        if request.method == "GET":
            if request.GET.get('name') != None:
                course = request.GET.get("course")
                course_data = get_course_str(course)
                tutor = extract_user_info(request.GET.get('tutor'))
                context = {'course': course_data[0] + " " + course_data[1], "tutor": tutor[0] + " " + tutor[1],

tutor_me/templates/tutor_me/availability.html
{% load static %}

{% block content %}
  <h5>Enter Your Availability</h5>
  <form method="post">
    {% csrf_token %}
    <label for="start">Start Time:</label> {{ form.start }}<br>
    <input type="datetime-local" id="start_time" name="start_time" required>
  </br>
    <label for="end">End Time:</label> {{ form.end }}<br>
    <input type="datetime-local" id="end_time" name="end_time" required>
    </br>
  </br>

    <button class = "btn btn-secondary" name="save_availability" type="submit">Save</button>
  </form>

</br>
</br>

{% endblock %}

tutor_me/templates/tutor_me/availability_list.html
{% load static %}


{% block content %}
<div class="timeslots-container">
{% for slot in timeslots %}
<div class = "timeslot">
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="delete_avail_id" value="{{ slot.id }}">
        <button type="submit" class="exit btn-close"></button>
    </form>
    <h6> Time Slot #{{ forloop.counter0|add:1 }} </h6>
    <p class="time"> Start Time: {{ slot.start }}</p>
    <p class="time"> End Time: {{ slot.end }}</p>
  </div>
  {% endfor %}
</div>

<h5>{{ message }}</h5>

{% endblock %}

tutor_me/templates/tutor_me/google_login.html
{% comment %}  
*  REFERENCES
*  Title: Building a Landing Page Using HTML and CSS
*  Author: Scaler
*  Date: 4/29/2023
*  URL: https://www.scaler.com/topics/landing-page-project-css/

*  Title: Study group photo
*  Author: Shutterstock
*  Date: 4/29/2023
*  URL: https://www.shutterstock.com/image-vector/happy-diverse-young-people-study-together-2071692923?irclickid=UrbwXZ3YExyNWD9X1bzm9xICUkAVkh0rEQlyyI0&irgwc=1&utm_campaign=TinEye&utm_content=108110&utm_medium=Affiliate&utm_source=77643&utm_term=

{% endcomment %}



{% load socialaccount %}
{% block content %}
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Login</title>
    <link rel="stylesheet" type="text/css" href="{% static 'tutor_me/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.3/css/all.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
        integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
</head>

<!--    hero section starts  -->

<section class="home" id="home ">
    <div class="content">
        
      <!-- Tagline -->
      <h3 class = "mainfont pb-2" style="font-weight:bold;"> Welcome to <span style="text-decoration:underline; text-decoration-style:dotted;"> TutorMe </span></h3>
      <h4> Get personalized academic support from the best tutors around UVA! </h4>
      <!--Description  -->
      <br>
      <p>
        From Organic Chemistry to Operating Systems, TutorMe will help connect you with top-notch tutors who provide one-on-one support for any course at UVA so you can reach your academic goals. Our application is easy to use and allows you to schedule sessions that fit your schedule. Join TutorMe today!
      </p>

      <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <button class="btn btn-info" style="font-size:18px;">
                <a class="no-underline" style="color:white;padding:12px" href="{% provider_login_url 'google' %}">
                    <i class="fab fa-google"></i>
                    Sign Up or Log In
                </a>
            </button>
        </div>
    </form>

    </div>
      
    <!-- Hero image -->

    <div class="image">
      <img src="{% static 'tutor_me/tutorphoto.png' %}" alt=" " />
    </div>
  </section>




    {% endblock %}

tutor_me/templates/tutor_me/notification.html
{% load static %}

{% block content %}
<div class="timeslots-container">
{% for notification in notifications %}
<div class = "timeslot">
    <form method="POST">
        {% csrf_token %}
        <input type="hidden" name="delete_notification_id" value="{{ notification.id }}">
        <button type="submit" class="exit btn-close"></button>
    </form>
    <h6> {{ notification.notification }} </h6>
  </div>
  {% endfor %}
</div>

{% endblock %}

tutor_me/templates/tutor_me/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Tutor Me Signup</title>
    {% load static %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'tutor_me/style.css' %}">
</head>

<body class="signup-form">
    <div class="signup">
        <h2>Select your user type below:</h2>
        <br>

        <form action="{% url 'tutor_me:redirect' %}" method="post">
            
            {% csrf_token %}
            {% for group in groups.all %}
            <input type="radio" name="group" id="group{{ forloop.counter }}" value="{{ group.id }}">
            <label style="font-size:2.4rem;" for="group{{ forloop.counter }}">{{ group }}
            </label> <br>
            {% endfor %}
            <br>
            <input class ="btn btn-info px-5" style="color:white; font-size:18px" type="submit" value="Submit">
        </form>
    </div>
</body>
</html>

tutor_me/templates/tutor_me/student_appointment.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'tutor_me/style.css' %}">
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
</head>

<body>

<div class="container" style="margin-top:50px">
        <h2>Start finding a tutor! Search for your desired class below.</h2>
          <div class="col-md-7">
              <form method="post">
                {% csrf_token %}
                <select class="class-dropdown select2" id="class-dropdown" name="class-dropdown">
                {% for class in classes %}
                    <option value="{{ class }}">{{ class }}</option>
                {% endfor %}
                </select>
                  <button type="submit">Find Tutor</button>
              </form>
          </div>
        <div class="col-md-7">
            {% for tutor in tutors %}
                {% for x in tutor %}
                    <button type="submit">{{ x }}</button>
                    <br><br>
                {% endfor %}
            {% endfor %}
        </div>

</div>
</body>

<script>
  $(document).ready(function() {
    $('.select2').select2();
  });
</script>

</html>

tutor_me/templates/tutor_me/student_view.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
    integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="{% static 'tutor_me/style.css' %}">
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
  <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/fullcalendar@6.1.5/index.global.min.js"></script>


  <style type="text/css">
    .popup {
      display: none;
      position: fixed;
      top: 75%;
      left: 50%;
      transform: translate(-50%, -50%);
      background-color: #fff;
      padding: 20px;
      box-shadow: 0 0 10px rgba(0, 0, 0, 0.5);
      text-align: center;
    }
  </style>
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link" href="/logout">Logout</a>
        </li>
      </ul>
    </div>
  </div>
</nav>


<body>

  <div class="container" style="margin-top:50px">
    <div class="row d-flex">

      <div class="col-md-12">
        <h2>Notifications</h2>
        <br><br>
        {% include 'tutor_me/notification.html' %}
        <br>
        <h2> Upcoming tutoring appointments </h2>
        <br>
        {% for appt in appointments %}
        <div class="card mb-3">
          <div class="card-block">
            <h4 class="card-title">{{ appt.tutor.first_name }} {{ appt.tutor.last_name }}</h4>
            <h6 class="card-subtitle text-muted pt-1 pb-3">{{ appt.course.mnemonic}} {{ appt.course.number}}: {{appt.course.name}}</h6>
            <p class="card-text p-y-1">{{ appt.note }}</p>
            <div class="detail">
              <h6>{{ appt.start.date }} </h6>
              <h6> {{ appt.start|time }} - {{ appt.end|time }}</h6>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>

      <div class="col-md-12">

        <h2>Start finding a tutor! Search for your desired class below.</h2>
        <div class="row">
          <div class="col-md-4">


              <form method="post">
                {% csrf_token %}
                <select class="class-dropdown select2" id="class-dropdown" name="class-dropdown" style="width:400px;font-size:16px;">
                  {% for class in classes %}
                  <option value="{{ class }}">{{ class }}</option>
                  {% endfor %}
                </select>
                <button class= "btn btn-secondary" type="submit" style="width:100px">Find Tutor</button>
              </form>

            <br>

        <H4>{{ message }}</H4>
            {% for tutor in tutors %}
            {% for x in tutor %}
            <form method="get">
              {% csrf_token %}
              <input type="hidden" name="course" value="{{ course }}">
              <input type="hidden" name="tutor" value="{{ x }}">
              <button type="submit" class="btn btn-outline-secondary" id="{{ x }}">{{ x }}</button>
              <textarea name="name" hidden>{{ x }}</textarea>
              <br><br>
            </form>
            {% endfor %}
            {% endfor %}
          </div>

          <div class="col-md-8">
            <div id='calendar'></div>
          </div>
        </div>
    </div>


  </div>
  </div>
</body>

{% if success_message %}
<script>
  alert('{{ success_message }}');

</script>
{% endif %}



<div class="popup" id="popup">
  <p>The request submitted successfully!</p>
  <button onclick="hidePopup()">Close</button>
</div>
<script type="text/javascript">
  function showPopup() {
    document.getElementById("popup").style.display = "block";
  }

  function hidePopup() {
    document.getElementById("popup").style.display = "none";
  }
</script>

<script>
  $(document).ready(function () {
    $('.select2').select2();
  });
</script>

<script type="text/javascript">
  var a = "{{ availabilities|safe }}";
  a = a.replace(/'/g, '"');
  var availabilities = JSON.parse(a);
  document.addEventListener('DOMContentLoaded', function () {
    var calendarEl = document.getElementById('calendar');
    var calendar = new FullCalendar.Calendar(calendarEl, {
      initialView: 'timeGridWeek',
      // set events to be the availabilities of the class
      events: availabilities,
      headerToolbar: {
        left: 'prev,next today',
        center: 'title',
        right: 'timeGridWeek,timeGridDay'
      },
      // change the color of the event to light blue
      eventColor: '#7FDBFF',
      // add a eventClick function to send a form as a get request
      eventClick: function (info) {
        // get the tutor button by id
        var title = info.event.title
        var start = info.event.start
        var date = getDate(start)
        start = dateFormat(start)
        var end = info.event.end
        end = dateFormat(end)
        var search = title + " is available on " + date + " from " + start + " to " + end + ". Appointment ID: " + info.event.id
        console.log(search)
        var tutorButton = document.getElementById(search);
        // Simulate a click on the tutor button
        tutorButton.click();
      },
      // make the event highlight only when the mouse hovers over it
      eventMouseEnter: function (info) {
        info.el.style.backgroundColor = '#0074D9';
      },
      eventMouseLeave: function (info) {
        info.el.style.backgroundColor = '#7FDBFF';
      },
    });
    calendar.render();
  })

  // create a function to convert date format
  function dateFormat(date) {
    var dateObj = new Date(date);
    var hours = dateObj.getHours();
    var minutes = dateObj.getMinutes();
    var meridian = hours >= 12 ? "PM" : "AM";
    // Convert to 12-hour format
    hours = hours % 12 || 12;
    // add a 0 in front of the hour if it is a single digit
    hours = hours < 10 ? "0" + hours : hours;
    var formattedTime = hours + ":" + (minutes < 10 ? "0" : "") + minutes + " " + meridian;
    var formatted = formattedTime;
    return formatted;
  }
  function getDate(date) {
    var dateObj = new Date(date)
    var day = dateObj.getDate();
    // var daySuffix = getDayNumberSuffix(day);
    var formattedDate = dateObj.toLocaleDateString('en-US', { month: 'long', day: '2-digit' });
    return formattedDate
  }
  
  // function getDayNumberSuffix(day) {
  //   switch (day) {
  //     case 1:
  //     case 21:
  //     case 31:
  //       return 'st';
  //     case 2:
  //     case 22:
  //       return 'nd';
  //     case 3:
  //     case 23:
  //       return 'rd';
  //     default:
  //       return 'th';
  //   }
  // }
</script>

</html>

tutor_me/templates/tutor_me/success.html
<h1>Appointment Request Submitted Successfully</h1>